### ISSUE TITLE
Add a scroll bar in the language Dropdown

### ISSUE THREAD

**Issue by version0chiro** [version0chiro/Find-Me-Issues#14]
## What To Do:

The drop down menu on the right side of the web-app does not have a scroll bar making it difficult to manage as the language support keeps increasing.

Limit the amount of active languages in the dropdown and add a scroll-bar to access all the languages below.

![image](https://user-images.githubusercontent.com/56084650/116822342-ff832f00-ab9b-11eb-99c3-8e2bbf769f0d.png)
Reference: right side drop down

Access the website here for a better reference : [here](https://find-me-issues.herokuapp.com/)

**Comment by Richa-09** [comment]
@version0chiro I have made the above changes. Please review my PR.

**Comment by version0chiro** [comment]
Good job on the issue @Richa-09

**Comment by Richa-09** [comment]
Thanks @version0chiro
