### ISSUE TITLE
Correct the spelling of "JavaScript" in `languages.json` and `App.js`

### ISSUE THREAD

**Issue by mohaimin5** [version0chiro/Find-Me-Issues#142]
### Summary
The word "JavaScript" is misspelled in "Javascript" (with a lowercase 's') in both the `languges.json` and `App.js`. While this does not affect the functionality of the application, correcting the spelling enhances the accuracy and professionalism of the project.
### Affected Files
- `languages.json`
- `App.js`
### Details
- In `languages.json`, within the list of programming languages, "JavaScript" is listed as "Javascript"
- In `App.js` the state variable `language` is initialized with the value "Javascript" instead of "JavaScript"
### Proposed Solution
- Update "Javascript" to "JavaScript" in the `languages.json` file
- Change the initial value of state variable `language` in `App.js` from "Javascritpt" to "JavaScript"
### Additional Context
- Correct spelling aligns with the official naming of the programming language.
- Improves the project's professionalism and attention to detail
### Request
I would like to work on this issue and submit a pull request  to implement the correction. Please let me know if this is acceptable.

**Comment by AshuJojo** [comment]
Hi @hasantohidul, is this issue still open? if so, may I work on this issue? I'm a first time open source contributor.

**Comment by mohaimin5** [comment]
Hey, @AshuJojo thank you for  your interest to contribute. However, somebody has already worked on the issue.

**Comment by AshuJojo** [comment]
Hello @hasantohidul, good to know that issue has been resolved. But if this (https://find-me-issues-web-app.netlify.app/ ) is your latest deployment with issue resolved, I guess the issue still persists. 
![Screenshot (8)](https://github.com/user-attachments/assets/f96dfc5a-3b09-46d7-bd67-2c6c6e7966d3)

Please let me know if I'm wrong. Thanks for your response.

**Comment by mohaimin5** [comment]
Hey, @AshuJojo  someone corrected the mistakes and make the pull request after I had raised the issue, but that has not been merged yet. I've just confirmed it. You can see it <a href="https://github.com/version0chiro/Find-Me-Issues/pull/145">here</a>. And that is why you did not see the change in deployment.

**Comment by AshuJojo** [comment]
Ok great! Thanks for your response @hasantohidul.
