### ISSUE TITLE
Filter Repositories on basis of repository's description 

### ISSUE THREAD

**Issue by version0chiro** [version0chiro/Find-Me-Issues#16]
## What to do:
- Filter the repositories returned from GitHub on  the basis of stars of repo, forks and the length of the description. You are free to implement your own algorithms to get this done.
- Research the GitHub API properly to understand how this can be done.

### Give a description of  how you would like to implement this and I will assign it to you. PR without proper descriptions will not be accepted.

**Comment by HunterX18** [comment]
Hello! Newbie here.
Do we have to sort the repositories page-wise or sort all the repos at once and then return 10 repos per page?
