### ISSUE TITLE
Broken layout on small viewport

### ISSUE THREAD

**Issue by EmanuelGF** [version0chiro/Find-Me-Issues#28]
**Describe the bug**
The layout is broken in small viewports. 

**To Reproduce**
1. start the project (yarn start on client).
2. Reduce the size of the viewport on whatever browser you are using.
3. Scroll down the issues list.
4. Look for out of place elements.

**Expected behavior**
Responsive layout.

**Screenshots**
![layout](https://user-images.githubusercontent.com/25751489/119223010-1065f700-baef-11eb-87d7-e127b9ee38b1.png)

**Additional context**
Since the project is using react-bootstrap I would suggest using Containers, Rows and Cols to achieve responsiveness.

**Comment by afif1400** [comment]
I would like to work on this.

**Comment by EmanuelGF** [comment]
I think its ok to close this . @version0chiro ?
