### ISSUE TITLE
Initiate a GitHub action to deploy to heroku automatically on push or branch merge

### ISSUE THREAD

**Issue by version0chiro** [version0chiro/Find-Me-Issues#34]
Create the steps of GitHub actions such that whenever a new push or merge request is made, it automates the task of deploying.

**Comment by jaimejusto** [comment]
I'd like to add this feature

**Comment by Dodger23** [comment]
Excuse me if I am wrong or don't fully understand the issue, but doesn't heroku already provide this feature? you can connect your GitHub account and select the repo, and heroku will automatically monitor any changes on it ( the selected branch ) and deploy whenever there is a new commit or merge ... etc

**Comment by version0chiro** [comment]
Thanks a lot @Dodger23 I had not seen the sync with Github on Heroku previously, I have added that now so it will automatically deploy 🙌

**Comment by jaimejusto** [comment]
I think the benefit of using GitHub actions would be that you can automate building and running of a test suite whenever changes are made to the main branch. You can also add some things like mandatory code reviews. Then, only if all the test cases pass will the pull request be processed and forwarded to someone to conduct a code review. Then once approved, it can automatically deploy to Heroku, if that makes sense.
