### ISSUE TITLE
Make the page changing div better

### ISSUE THREAD

**Issue by version0chiro** [version0chiro/Find-Me-Issues#4]
## What to do:
Design a sleek looking design for the page number division that can be found in [Navigation.js](client/src/components/Navigation.js)

You can use material.ui and react bootstrap as they are part of the project already.

**Comment by nicyuvi** [comment]
Hi @version0chiro if it's still open I'd like to take this issue (first timer!)

**Comment by version0chiro** [comment]
Go ahead @nicyuvi , I have assigned you with the project! Send a PR and explain the changes you have made on it and I will merge it!

**Comment by version0chiro** [comment]
Any progress ? @nicyuvi

**Comment by nicyuvi** [comment]
I got busy but I will submit a PR today! @version0chiro
