### ISSUE TITLE
Heroku app not working

### ISSUE THREAD

**Issue by labala-sravani** [version0chiro/Find-Me-Issues#64]
https://find-me-issues.herokuapp.com/ is not working currently.

<img width="1132" alt="Screenshot 2023-01-02 at 8 10 18 PM" src="https://user-images.githubusercontent.com/73987889/210246024-b4bce42a-83a8-4b9a-b0e6-d625a8d20824.png">

@version0chiro Please help to check the logs and fix the issue.

And let me know once it is fixed, I would like to contribute to the project.
Thanks.

**Comment by Shaikhaltamash861** [comment]
assign this to me?

**Comment by version0chiro** [comment]
Hey will be picking up revamp of this project and rehost it onto a server for everyone to be able to contribute
