### ISSUE TITLE
Emoji fails to load

### ISSUE THREAD

**Issue by version0chiro** [version0chiro/Find-Me-Issues#7]
## What to do?
![image](https://user-images.githubusercontent.com/56084650/116748330-ef911100-aa1c-11eb-8d99-c59bc1d31965.png)

As the description is taken from GitHub's API and passed as a prop, sometimes emojis fails to load in description.  Try to fix this issue such that all emojis load without any problem.

**Comment by punndcoder28** [comment]
Hi @version0chiro . I would like to take this issue up. As far as I can understand we need a map for string to the equivalent unicode value. Should I see which libraries do this or do we need a raw map which has the right values. I feel using a prebuilt library is a much easier approach.

**Comment by version0chiro** [comment]
@punndcoder28 yes, using a library will make the job easy. You can take this up and try it any way that seems good to you and send a PR accordingly.

**Comment by punndcoder28** [comment]
Open PR #9 to fix this issue @version0chiro

**Comment by version0chiro** [comment]
Good job on the request @punndcoder28! Continue open sourcing  and feel free to drop any suggestion for future features.

**Comment by version0chiro** [comment]
@punndcoder28  The code is currently rendering the html as text file, please fix this and resend a PR
![image](https://user-images.githubusercontent.com/56084650/116777080-f30eb180-aa89-11eb-8f52-8a8c3bcb60de.png)

**Comment by version0chiro** [comment]
> @punndcoder28 The code is currently rendering the html as text file, please fix this and resend a PR
> ![image](https://user-images.githubusercontent.com/56084650/116777080-f30eb180-aa89-11eb-8f52-8a8c3bcb60de.png)

Run the app on your local machine to check.

**Comment by punndcoder28** [comment]
@version0chiro will check must be a mistake from my side

**Comment by punndcoder28** [comment]
@version0chiro it is working as expected on my system.
<img width="854" alt="Screenshot 2021-05-02 at 1 00 36 PM" src="https://user-images.githubusercontent.com/32433964/116805795-6544cc00-ab46-11eb-80e6-825764fecd83.png">

**Comment by version0chiro** [comment]
Alright, Send another PR if it is working on your end, must be some server related issue.

**Comment by punndcoder28** [comment]
I am guessing you did `rpm install` before running 😄

**Comment by punndcoder28** [comment]
Created new PR #12  @version0chiro
