### ISSUE TITLE
Throwing error during starting the server in codespace (Unsupported and outdated version).

### ISSUE THREAD

**Issue by Tissu07** [version0chiro/Find-Me-Issues#78]
**Describe the bug**
Specifically mentions an "unsupported" operation in the OpenSSL library. Additionally, there is a warning about an outdated version of "caniuse-lite" which is related to browser compatibility data.

**To Reproduce**
When I try to start the server in codespace I find this error. I used "npm run start" command.

**Expected behavior**
It should have started the server but didn't. It throws errors that make a bad impression.

**Screenshot **
![issue](https://github.com/version0chiro/Find-Me-Issues/assets/110936472/352a4676-f19a-41a9-8575-3f9424d4b30e)

**Comment by r-a-j-s-i-n-h-a** [comment]
try updating NodeJs version
Uninstall Nodejs 
Install it again Nodejs 16.13.0 version

**Comment by AGENTSJ** [comment]
Is this issue assigned to any one if not i can work on it

**Comment by version0chiro** [comment]
Hey Guys The following issues has been due to an outdated version of react-scripts, I have fixed the issue so that we do not have to downgrade the node version. please refer the following Issue: https://github.com/version0chiro/Find-Me-Issues/issues/85
