### ISSUE TITLE
Newly Revamped Navbar + "Filter" Section

### ISSUE THREAD

**Issue by CarrumDraws** [version0chiro/Find-Me-Issues#95]
Hello! I noticed that this app's Navbar and Filters section could use some redesigning. I am a professional Graphic Designer and I'm looking into contributing to opensource, so I'd be honored if I was given the opportunity to redesign these sections of your app!

Here are my proposals: 
1. Merge "Select language" and "Search Bar" into a single "double search bar" like the one on Indeed.com.
2. Create a new "Filters" section that combines the page-search bar and the "Filters" dropdown into a single line
3. Move "Sort By Stars" and "Sort By Forks" to a new "Sort By" button that is attached to the "Filters" section
4. Make everything responsive, so it works on mobile devices

![IMG_1588](https://github.com/version0chiro/Find-Me-Issues/assets/47155634/6feb6fcb-e117-487d-b899-154f772d2b06)

I firmly believe that these changes would modernize the look of the app and lead to a significantly improved user experience. 
This would be my first opensource contribution, but I'm excited to learn about the opensource workflow. If it goes smoothly I could even design a new logo for the site!

**Comment by version0chiro** [comment]
Hey, this is great! Thanks for the inputs will update the tags so someone can pick it up as an enhancement!

**Comment by CarrumDraws** [comment]
Yeah I'd love to pick it up if possible! :)
